# Generated by Django 4.0 on 2022-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='ta',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
