# Generated by Django 4.0 on 2022-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_alter_salary_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='ta',
            field=models.BooleanField(default=False),
        ),
    ]
