# Generated by Django 3.2.12 on 2022-04-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
