# Generated by Django 3.2.12 on 2022-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic_pay',
            field=models.FloatField(),
        ),
    ]
