# Generated by Django 3.2.12 on 2022-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_alter_salary_basic_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
