# Generated by Django 3.2.12 on 2022-04-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='basic',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hra',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other_benefits',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other_deductions',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pf',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='ta',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_pay',
            field=models.BigIntegerField(),
        ),
    ]
