# Generated by Django 4.0 on 2022-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='last_apply',
            field=models.DateField(null=True),
        ),
    ]
