# Generated by Django 4.0 on 2022-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
