# Generated by Django 4.0 on 2022-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_applicantprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Newuser',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='email',
        ),
    ]
