# Generated by Django 4.0 on 2022-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_applicantprofile_last_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='addressline1',
            field=models.CharField(default='', max_length=60),
        ),
    ]
