# Generated by Django 4.0 on 2022-02-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0003_rename_login_newuser_remove_applicantprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newuser',
            new_name='Login',
        ),
    ]
