# Generated by Django 4.0 on 2022-02-22 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_applicantprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='cv',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
