# Generated by Django 4.0 on 2022-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_applicantprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
    ]
