# Generated by Django 4.0 on 2022-02-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_rename_newuser_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Newuser',
        ),
    ]
