# Generated by Django 4.0 on 2022-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_login_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
