# Generated by Django 4.0 on 2022-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
