# Generated by Django 4.0 on 2022-03-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nil', 'Prefer Not to Say')], max_length=10),
        ),
    ]
