# Generated by Django 4.0 on 2022-02-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_applicantprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_project_manager',
        ),
    ]
