# Generated by Django 4.0 on 2022-03-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_applicantprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nil', 'Nil')], max_length=10),
        ),
    ]
