# Generated by Django 3.2.12 on 2022-03-30 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicantprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='cv',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
