# Generated by Django 4.0 on 2022-02-08 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_applicantprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digit number.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pin must be 6 digit number', regex='^\\+?1?\\d{6}$')]),
        ),
    ]
