# Generated by Django 4.0 on 2022-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
        ('base', '0007_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('dob', models.DateField(null=True)),
                ('addressline1', models.CharField(default='', max_length=60)),
                ('place', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('join_date', models.DateField()),
                ('pin', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
    ]
