# Generated by Django 4.0 on 2022-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeeprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
