# Generated by Django 4.0 on 2022-03-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='Department',
        ),
    ]
