# Generated by Django 4.0 on 2022-03-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
        ('employees', '0004_remove_employeeprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
    ]
