# Generated by Django 4.0 on 2022-03-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
        ('employees', '0006_alter_attendance_entry_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightshift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nightshift_date', models.DateField()),
                ('entry_time', models.TimeField(null=True)),
                ('exit_time', models.TimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
    ]
