# Generated by Django 4.0 on 2022-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_nightshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Nightshift',
        ),
    ]
