# Generated by Django 4.0 on 2022-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_attendance_shift_delete_nightshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(default='', max_length=10),
        ),
    ]
