# Generated by Django 4.0 on 2022-03-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
        ('employees', '0009_alter_attendance_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(auto_now_add=True)),
                ('leave_type', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
    ]
