# Generated by Django 4.0 on 2022-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='from_session',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='leave',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='to_session',
            field=models.CharField(default='', max_length=10),
        ),
    ]
