# Generated by Django 4.0 on 2022-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_leave_leave_date_leave_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='from_session',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_session',
            field=models.CharField(max_length=10),
        ),
    ]
