# Generated by Django 4.0 on 2022-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_leave_from_date_alter_leave_from_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
