# Generated by Django 4.0 on 2022-03-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_department_options_and_more'),
        ('admin', '0002_designations'),
        ('employees', '0015_alter_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.designations'),
        ),
    ]
