# Generated by Django 4.0 on 2022-03-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
    ]
