# Generated by Django 4.0 on 2022-03-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_designations'),
        ('base', '0007_alter_department_options_and_more'),
        ('employees', '0019_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.designations'),
        ),
    ]
