# Generated by Django 4.0 on 2022-03-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_designations'),
        ('base', '0007_alter_department_options_and_more'),
        ('employees', '0021_alter_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='designation',
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.designations')),
            ],
        ),
    ]
