# Generated by Django 4.0 on 2022-03-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantprofile_phone_and_more'),
        ('employees', '0022_remove_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedesignation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.newuser'),
        ),
    ]
