# Generated by Django 4.0 on 2022-03-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_employeedesignation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='join_date',
        ),
    ]
