# Generated by Django 4.0 on 2022-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_leave_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(max_length=20),
        ),
    ]
