# Generated by Django 4.0 on 2022-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
