# Generated by Django 4.0 on 2022-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_leave_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
