# Generated by Django 4.0 on 2022-03-23 05:07

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_alter_leave_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(validators=[employees.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(validators=[employees.models.validate_date]),
        ),
    ]
