# Generated by Django 4.0 on 2022-03-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicantprofile_gender'),
        ('employees', '0031_alter_leave_from_date_alter_leave_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegulization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('old_entry', models.TimeField()),
                ('new_entry', models.TimeField()),
                ('old_exit', models.TimeField()),
                ('new_exit', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
    ]
