# Generated by Django 4.0 on 2022-03-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicantprofile_gender'),
        ('employees', '0032_attendanceregulization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRegulization',
            new_name='AttendanceRegularization',
        ),
    ]
