# Generated by Django 3.2.12 on 2022-03-30 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0033_rename_attendanceregulization_attendanceregularization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.FloatField()),
                ('el', models.FloatField()),
                ('lp', models.FloatField()),
                ('sl', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
