# Generated by Django 3.2.12 on 2022-03-30 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_leavecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attachments',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
