# Generated by Django 3.2.12 on 2022-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_alter_attendance_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
