# Generated by Django 3.2.12 on 2022-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_attendance_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lno',
            field=models.IntegerField(default=0),
        ),
    ]
