# Generated by Django 3.2.12 on 2022-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_attendance_lno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lno',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave',
            field=models.BooleanField(default=False),
        ),
    ]
