# Generated by Django 3.2.12 on 2022-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_leave_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecounter',
            name='date',
            field=models.DateField(),
        ),
    ]
