# Generated by Django 3.2.12 on 2022-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_alter_leavecounter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregularization',
            name='shift',
            field=models.CharField(default='', max_length=10),
        ),
    ]
