# Generated by Django 3.2.12 on 2022-04-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_attendanceregularization_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
