# Generated by Django 4.0 on 2022-02-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_department_options_and_more'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobs')),
            ],
        ),
    ]
