# Generated by Django 4.0 on 2022-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
