# Generated by Django 4.0 on 2022-03-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_interviews_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='selected',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
