# Generated by Django 4.0 on 2022-03-27 04:16

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applications_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='interview_date',
            field=models.DateField(validators=[applicants.models.validate_date]),
        ),
    ]
