# Generated by Django 3.2.12 on 2022-04-03 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 12, 33, 1, 607150)),
        ),
    ]
