# Generated by Django 3.2.12 on 2022-04-04 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 17, 5, 29, 784690)),
        ),
    ]
