# Generated by Django 4.0 on 2022-02-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_jobs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Location',
            new_name='location',
        ),
    ]
