# Generated by Django 4.0 on 2022-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_options_alter_jobs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
