# Generated by Django 4.0 on 2022-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_jobs_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
