# Generated by Django 4.0 on 2022-02-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_jobs_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Department',
        ),
    ]
