# Generated by Django 4.0 on 2022-02-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_category_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Department'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='category',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='category',
            new_name='department',
        ),
    ]
