# Generated by Django 4.0 on 2022-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
