# Generated by Django 4.0 on 2022-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_jobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
