# Generated by Django 4.0 on 2022-03-23 05:38

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_jobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='withdraw_date',
            field=models.DateField(validators=[base.models.validate_date]),
        ),
    ]
